name: TEK5030
title: TEK5030
description: TEK5030 resource pages
url: "https://tek5030.github.io"
markdown: GFM
highlighter: rouge
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme