var searchData=
[
  ['cache',['Cache',['http://docs.opencv.org/4.0.1/da/da5/structcv_1_1gapi_1_1fluid_1_1View_1_1Cache.html',1,'cv::gapi::fluid::View::Cache'],['http://docs.opencv.org/4.0.1/dc/dd8/structcv_1_1gapi_1_1fluid_1_1Buffer_1_1Cache.html',1,'cv::gapi::fluid::Buffer::Cache']]],
  ['calibratecrf',['CalibrateCRF',['http://docs.opencv.org/4.0.1/dd/de3/classcv_1_1CalibrateCRF.html',1,'cv']]],
  ['calibratedebevec',['CalibrateDebevec',['http://docs.opencv.org/4.0.1/da/d27/classcv_1_1CalibrateDebevec.html',1,'cv']]],
  ['calibraterobertson',['CalibrateRobertson',['http://docs.opencv.org/4.0.1/d3/d30/classcv_1_1CalibrateRobertson.html',1,'cv']]],
  ['call_5fand_5fpostprocess',['call_and_postprocess',['http://docs.opencv.org/4.0.1/df/de6/structcv_1_1detail_1_1OCVCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_1tu8bfb77c34485398698447f60ee067830.html',1,'cv::detail::OCVCallHelper::call_and_postprocess&lt; Inputs &gt;'],['http://docs.opencv.org/4.0.1/d5/def/structcv_1_1detail_1_1OCLCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_1tua67cc2fc13da93c8cd58afcdf4d9cddf.html',1,'cv::detail::OCLCallHelper::call_and_postprocess&lt; Inputs &gt;']]],
  ['callback',['Callback',['http://docs.opencv.org/4.0.1/d8/d9f/classcv_1_1LMSolver_1_1Callback.html',1,'cv::LMSolver::Callback'],['http://docs.opencv.org/4.0.1/d0/d4f/classcv_1_1text_1_1ERFilter_1_1Callback.html',1,'cv::text::ERFilter::Callback']]],
  ['callmetadata',['CallMetaData',['http://docs.opencv.org/4.0.1/d4/dd9/structcvv_1_1impl_1_1CallMetaData.html',1,'cvv::impl']]],
  ['camera',['Camera',['http://docs.opencv.org/4.0.1/dc/d3a/classcv_1_1viz_1_1Camera.html',1,'cv::viz']]],
  ['cameraparam',['cameraParam',['http://docs.opencv.org/4.0.1/d3/d99/structcv_1_1datasets_1_1cameraParam.html',1,'cv::datasets']]],
  ['cameraparams',['CameraParams',['http://docs.opencv.org/4.0.1/d4/d0a/structcv_1_1detail_1_1CameraParams.html',1,'cv::detail']]],
  ['camerapos',['cameraPos',['http://docs.opencv.org/4.0.1/d1/d64/structcv_1_1datasets_1_1cameraPos.html',1,'cv::datasets']]],
  ['candidate',['Candidate',['http://docs.opencv.org/4.0.1/df/da3/structcv_1_1linemod_1_1QuantizedPyramid_1_1Candidate.html',1,'cv::linemod::QuantizedPyramid']]],
  ['cannyedgedetector',['CannyEdgeDetector',['http://docs.opencv.org/4.0.1/d0/d43/classcv_1_1cuda_1_1CannyEdgeDetector.html',1,'cv::cuda']]],
  ['cascadeclassifier',['CascadeClassifier',['http://docs.opencv.org/4.0.1/d1/de5/classcv_1_1CascadeClassifier.html',1,'cv::CascadeClassifier'],['http://docs.opencv.org/4.0.1/d9/d80/classcv_1_1cuda_1_1CascadeClassifier.html',1,'cv::cuda::CascadeClassifier']]],
  ['censuskernel',['CensusKernel',['http://docs.opencv.org/4.0.1/dc/d9a/structcv_1_1stereo_1_1CensusKernel.html',1,'cv::stereo']]],
  ['channelsprelulayer',['ChannelsPReLULayer',['http://docs.opencv.org/4.0.1/d7/de9/classcv_1_1dnn_1_1ChannelsPReLULayer.html',1,'cv::dnn']]],
  ['charucoboard',['CharucoBoard',['http://docs.opencv.org/4.0.1/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html',1,'cv::aruco']]],
  ['check',['check',['http://docs.opencv.org/4.0.1/dd/d16/classcv_1_1detail_1_1has__custom__wrap_1_1check.html',1,'cv::detail::has_custom_wrap']]],
  ['chihistogramcostextractor',['ChiHistogramCostExtractor',['http://docs.opencv.org/4.0.1/dd/d43/classcv_1_1ChiHistogramCostExtractor.html',1,'cv']]],
  ['chisquaredistance',['ChiSquareDistance',['http://docs.opencv.org/4.0.1/dd/dd8/structcvflann_1_1ChiSquareDistance.html',1,'cvflann']]],
  ['choose_5fpolicy',['choose_policy',['http://docs.opencv.org/4.0.1/d5/da1/structcvflann_1_1anyimpl_1_1choose__policy.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20any_20_3e',['choose_policy&lt; any &gt;',['http://docs.opencv.org/4.0.1/d5/d51/structcvflann_1_1anyimpl_1_1choose__policy_3_01any_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20bool_20_3e',['choose_policy&lt; bool &gt;',['http://docs.opencv.org/4.0.1/d9/d10/structcvflann_1_1anyimpl_1_1choose__policy_3_01bool_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20float_20_3e',['choose_policy&lt; float &gt;',['http://docs.opencv.org/4.0.1/d2/d87/structcvflann_1_1anyimpl_1_1choose__policy_3_01float_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20char_20_3e',['choose_policy&lt; signed char &gt;',['http://docs.opencv.org/4.0.1/dc/d84/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20long_20_3e',['choose_policy&lt; signed long &gt;',['http://docs.opencv.org/4.0.1/d7/d22/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20short_20_3e',['choose_policy&lt; signed short &gt;',['http://docs.opencv.org/4.0.1/d3/d4a/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20char_20_3e',['choose_policy&lt; unsigned char &gt;',['http://docs.opencv.org/4.0.1/dd/dd1/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20long_20_3e',['choose_policy&lt; unsigned long &gt;',['http://docs.opencv.org/4.0.1/d9/dcd/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20short_20_3e',['choose_policy&lt; unsigned short &gt;',['http://docs.opencv.org/4.0.1/d9/dd6/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['circlesgridfinderparameters',['CirclesGridFinderParameters',['http://docs.opencv.org/4.0.1/d2/dd1/structcv_1_1CirclesGridFinderParameters.html',1,'cv']]],
  ['clahe',['CLAHE',['http://docs.opencv.org/4.0.1/d6/db6/classcv_1_1CLAHE.html',1,'cv::CLAHE'],['http://docs.opencv.org/4.0.1/db/d79/classcv_1_1cuda_1_1CLAHE.html',1,'cv::cuda::CLAHE']]],
  ['classifiercallback',['ClassifierCallback',['http://docs.opencv.org/4.0.1/db/dc0/classcv_1_1text_1_1OCRHMMDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRHMMDecoder::ClassifierCallback'],['http://docs.opencv.org/4.0.1/de/d2d/classcv_1_1text_1_1OCRBeamSearchDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRBeamSearchDecoder::ClassifierCallback']]],
  ['classifierthreshold',['ClassifierThreshold',['http://docs.opencv.org/4.0.1/d7/dd9/classcv_1_1ClassifierThreshold.html',1,'cv']]],
  ['clfmilboost',['ClfMilBoost',['http://docs.opencv.org/4.0.1/dc/d72/classcv_1_1ClfMilBoost.html',1,'cv']]],
  ['clfonlinestump',['ClfOnlineStump',['http://docs.opencv.org/4.0.1/dc/dac/classcv_1_1ClfOnlineStump.html',1,'cv']]],
  ['color',['Color',['http://docs.opencv.org/4.0.1/d4/dba/classcv_1_1viz_1_1Color.html',1,'cv::viz']]],
  ['coloraverageinpainter',['ColorAverageInpainter',['http://docs.opencv.org/4.0.1/d1/dc6/classcv_1_1videostab_1_1ColorAverageInpainter.html',1,'cv::videostab']]],
  ['colorgradient',['ColorGradient',['http://docs.opencv.org/4.0.1/dc/d64/classcv_1_1linemod_1_1ColorGradient.html',1,'cv::linemod']]],
  ['colorinpainter',['ColorInpainter',['http://docs.opencv.org/4.0.1/d3/d2b/classcv_1_1videostab_1_1ColorInpainter.html',1,'cv::videostab']]],
  ['colormomenthash',['ColorMomentHash',['http://docs.opencv.org/4.0.1/df/d52/classcv_1_1img__hash_1_1ColorMomentHash.html',1,'cv::img_hash']]],
  ['combineddescriptor',['CombinedDescriptor',['http://docs.opencv.org/4.0.1/d4/d5b/classcv_1_1stereo_1_1CombinedDescriptor.html',1,'cv::stereo']]],
  ['commandlineparser',['CommandLineParser',['http://docs.opencv.org/4.0.1/d0/d2e/classcv_1_1CommandLineParser.html',1,'cv']]],
  ['commonareainterptr',['CommonAreaInterPtr',['http://docs.opencv.org/4.0.1/d8/d3d/structcv_1_1cudev_1_1CommonAreaInterPtr.html',1,'cv::cudev']]],
  ['commonareainterptrsz',['CommonAreaInterPtrSz',['http://docs.opencv.org/4.0.1/db/d1c/structcv_1_1cudev_1_1CommonAreaInterPtrSz.html',1,'cv::cudev']]],
  ['comparet',['CompareT',['http://docs.opencv.org/4.0.1/d2/d76/structcvflann_1_1Heap_1_1CompareT.html',1,'cvflann::Heap']]],
  ['compileargtag',['CompileArgTag',['http://docs.opencv.org/4.0.1/dd/d3d/structcv_1_1detail_1_1CompileArgTag.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3agkernelpackage_20_3e',['CompileArgTag&lt; cv::gapi::GKernelPackage &gt;',['http://docs.opencv.org/4.0.1/d5/d58/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1GKernelPackage_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agapi_3a_3aglookuporder_20_3e',['CompileArgTag&lt; cv::gapi::GLookupOrder &gt;',['http://docs.opencv.org/4.0.1/df/d3d/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1gapi_1_1GLookupOrder_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20cv_3a_3agraph_5fdump_5fpath_20_3e',['CompileArgTag&lt; cv::graph_dump_path &gt;',['http://docs.opencv.org/4.0.1/d3/d64/structcv_1_1detail_1_1CompileArgTag_3_01cv_1_1graph__dump__path_01_4.html',1,'cv::detail']]],
  ['compileargtag_3c_20gfluidoutputrois_20_3e',['CompileArgTag&lt; GFluidOutputRois &gt;',['http://docs.opencv.org/4.0.1/d7/d5e/structcv_1_1detail_1_1CompileArgTag_3_01GFluidOutputRois_01_4.html',1,'cv::detail']]],
  ['complex',['Complex',['http://docs.opencv.org/4.0.1/da/df6/classcv_1_1Complex.html',1,'cv']]],
  ['compositeindex',['CompositeIndex',['http://docs.opencv.org/4.0.1/dc/d59/classcvflann_1_1CompositeIndex.html',1,'cvflann']]],
  ['compositeindexparams',['CompositeIndexParams',['http://docs.opencv.org/4.0.1/db/d3f/structcvflann_1_1CompositeIndexParams.html',1,'cvflann::CompositeIndexParams'],['http://docs.opencv.org/4.0.1/d5/d94/structcv_1_1flann_1_1CompositeIndexParams.html',1,'cv::flann::CompositeIndexParams']]],
  ['compressedrectilinearportraitprojector',['CompressedRectilinearPortraitProjector',['http://docs.opencv.org/4.0.1/d0/ded/structcv_1_1detail_1_1CompressedRectilinearPortraitProjector.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['http://docs.opencv.org/4.0.1/dd/dc8/classcv_1_1detail_1_1CompressedRectilinearPortraitWarper.html',1,'cv::detail::CompressedRectilinearPortraitWarper'],['http://docs.opencv.org/4.0.1/de/d9a/classcv_1_1CompressedRectilinearPortraitWarper.html',1,'cv::CompressedRectilinearPortraitWarper']]],
  ['compressedrectilinearprojector',['CompressedRectilinearProjector',['http://docs.opencv.org/4.0.1/db/dbb/structcv_1_1detail_1_1CompressedRectilinearProjector.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['http://docs.opencv.org/4.0.1/dd/dbe/classcv_1_1detail_1_1CompressedRectilinearWarper.html',1,'cv::detail::CompressedRectilinearWarper'],['http://docs.opencv.org/4.0.1/d0/dd5/classcv_1_1CompressedRectilinearWarper.html',1,'cv::CompressedRectilinearWarper']]],
  ['concatlayer',['ConcatLayer',['http://docs.opencv.org/4.0.1/da/d5c/classcv_1_1dnn_1_1ConcatLayer.html',1,'cv::dnn']]],
  ['config',['Config',['http://docs.opencv.org/4.0.1/d0/ded/structcv_1_1face_1_1FacemarkAAM_1_1Config.html',1,'cv::face::FacemarkAAM']]],
  ['conjgradsolver',['ConjGradSolver',['http://docs.opencv.org/4.0.1/d0/d21/classcv_1_1ConjGradSolver.html',1,'cv']]],
  ['consistentmosaicinpainter',['ConsistentMosaicInpainter',['http://docs.opencv.org/4.0.1/d9/dba/classcv_1_1videostab_1_1ConsistentMosaicInpainter.html',1,'cv::videostab']]],
  ['constantptr',['ConstantPtr',['http://docs.opencv.org/4.0.1/d5/db7/structcv_1_1cudev_1_1ConstantPtr.html',1,'cv::cudev']]],
  ['constantptrsz',['ConstantPtrSz',['http://docs.opencv.org/4.0.1/d2/df7/structcv_1_1cudev_1_1ConstantPtrSz.html',1,'cv::cudev']]],
  ['constlayer',['ConstLayer',['http://docs.opencv.org/4.0.1/de/dff/classcv_1_1dnn_1_1ConstLayer.html',1,'cv::dnn']]],
  ['context',['Context',['http://docs.opencv.org/4.0.1/d1/d45/classcv_1_1ocl_1_1Context.html',1,'cv::ocl']]],
  ['contourfitting',['ContourFitting',['http://docs.opencv.org/4.0.1/d5/d72/classcv_1_1ximgproc_1_1ContourFitting.html',1,'cv::ximgproc']]],
  ['converttuple',['ConvertTuple',['http://docs.opencv.org/4.0.1/d9/d6a/structcv_1_1cudev_1_1ConvertTuple.html',1,'cv::cudev']]],
  ['convolution',['Convolution',['http://docs.opencv.org/4.0.1/d4/d25/classcv_1_1cuda_1_1Convolution.html',1,'cv::cuda']]],
  ['convolutionlayer',['ConvolutionLayer',['http://docs.opencv.org/4.0.1/d5/dcf/classcv_1_1dnn_1_1ConvolutionLayer.html',1,'cv::dnn']]],
  ['cornernesscriteria',['CornernessCriteria',['http://docs.opencv.org/4.0.1/dd/d63/classcv_1_1cuda_1_1CornernessCriteria.html',1,'cv::cuda']]],
  ['cornersdetector',['CornersDetector',['http://docs.opencv.org/4.0.1/de/d95/classcv_1_1cuda_1_1CornersDetector.html',1,'cv::cuda']]],
  ['cos_5ffunc',['cos_func',['http://docs.opencv.org/4.0.1/d6/dfb/structcv_1_1cudev_1_1cos__func.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20double_20_3e',['cos_func&lt; double &gt;',['http://docs.opencv.org/4.0.1/db/d23/structcv_1_1cudev_1_1cos__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20float_20_3e',['cos_func&lt; float &gt;',['http://docs.opencv.org/4.0.1/dd/d7a/structcv_1_1cudev_1_1cos__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20schar_20_3e',['cos_func&lt; schar &gt;',['http://docs.opencv.org/4.0.1/dc/d25/structcv_1_1cudev_1_1cos__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20short_20_3e',['cos_func&lt; short &gt;',['http://docs.opencv.org/4.0.1/d7/d03/structcv_1_1cudev_1_1cos__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uchar_20_3e',['cos_func&lt; uchar &gt;',['http://docs.opencv.org/4.0.1/dd/d3d/structcv_1_1cudev_1_1cos__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uint_20_3e',['cos_func&lt; uint &gt;',['http://docs.opencv.org/4.0.1/da/dc1/structcv_1_1cudev_1_1cos__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20ushort_20_3e',['cos_func&lt; ushort &gt;',['http://docs.opencv.org/4.0.1/df/d35/structcv_1_1cudev_1_1cos__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc',['cosh_func',['http://docs.opencv.org/4.0.1/dc/d8a/structcv_1_1cudev_1_1cosh__func.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20double_20_3e',['cosh_func&lt; double &gt;',['http://docs.opencv.org/4.0.1/d5/d3a/structcv_1_1cudev_1_1cosh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20float_20_3e',['cosh_func&lt; float &gt;',['http://docs.opencv.org/4.0.1/db/d8d/structcv_1_1cudev_1_1cosh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20schar_20_3e',['cosh_func&lt; schar &gt;',['http://docs.opencv.org/4.0.1/df/dd8/structcv_1_1cudev_1_1cosh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20short_20_3e',['cosh_func&lt; short &gt;',['http://docs.opencv.org/4.0.1/dc/d8a/structcv_1_1cudev_1_1cosh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uchar_20_3e',['cosh_func&lt; uchar &gt;',['http://docs.opencv.org/4.0.1/de/d73/structcv_1_1cudev_1_1cosh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uint_20_3e',['cosh_func&lt; uint &gt;',['http://docs.opencv.org/4.0.1/d5/ddd/structcv_1_1cudev_1_1cosh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20ushort_20_3e',['cosh_func&lt; ushort &gt;',['http://docs.opencv.org/4.0.1/d2/dd3/structcv_1_1cudev_1_1cosh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['countnonzeroexprbody',['CountNonZeroExprBody',['http://docs.opencv.org/4.0.1/dd/d49/structcv_1_1cudev_1_1CountNonZeroExprBody.html',1,'cv::cudev']]],
  ['cparams',['CParams',['http://docs.opencv.org/4.0.1/d8/dd8/structcv_1_1face_1_1CParams.html',1,'cv::face']]],
  ['creatornotfound',['CreatorNotFound',['http://docs.opencv.org/4.0.1/db/d35/classcvflann_1_1CreatorNotFound.html',1,'cvflann']]],
  ['cropandresizelayer',['CropAndResizeLayer',['http://docs.opencv.org/4.0.1/d8/d53/classcv_1_1dnn_1_1CropAndResizeLayer.html',1,'cv::dnn']]],
  ['croplayer',['CropLayer',['http://docs.opencv.org/4.0.1/d7/d86/classcv_1_1dnn_1_1CropLayer.html',1,'cv::dnn']]],
  ['ct_5fassert_5ffailure',['CT_ASSERT_FAILURE',['http://docs.opencv.org/4.0.1/da/d73/structNcvCTprep_1_1CT__ASSERT__FAILURE.html',1,'NcvCTprep']]],
  ['ct_5fassert_5ffailure_3c_20true_20_3e',['CT_ASSERT_FAILURE&lt; true &gt;',['http://docs.opencv.org/4.0.1/dc/dcf/structNcvCTprep_1_1CT__ASSERT__FAILURE_3_01true_01_4.html',1,'NcvCTprep']]],
  ['cubicinterptr',['CubicInterPtr',['http://docs.opencv.org/4.0.1/d3/def/structcv_1_1cudev_1_1CubicInterPtr.html',1,'cv::cudev']]],
  ['cubicinterptrsz',['CubicInterPtrSz',['http://docs.opencv.org/4.0.1/d2/d00/structcv_1_1cudev_1_1CubicInterPtrSz.html',1,'cv::cudev']]],
  ['custompattern',['CustomPattern',['http://docs.opencv.org/4.0.1/d3/d3e/classcv_1_1ccalib_1_1CustomPattern.html',1,'cv::ccalib']]],
  ['cv16suf',['Cv16suf',['http://docs.opencv.org/4.0.1/dd/d0f/unionCv16suf.html',1,'']]],
  ['cv32suf',['Cv32suf',['http://docs.opencv.org/4.0.1/d9/df3/unionCv32suf.html',1,'']]],
  ['cv64suf',['Cv64suf',['http://docs.opencv.org/4.0.1/de/d55/unionCv64suf.html',1,'']]],
  ['cv_5ffinal',['CV_FINAL',['http://docs.opencv.org/4.0.1/da/dbd/structcvflann_1_1anyimpl_1_1CV__FINAL.html',1,'cvflann::anyimpl']]],
  ['cvabstractcamera',['CvAbstractCamera',['http://docs.opencv.org/4.0.1/d0/de8/interfaceCvAbstractCamera.html',1,'']]],
  ['cvfeatureevaluator',['CvFeatureEvaluator',['http://docs.opencv.org/4.0.1/d0/d0b/classcv_1_1CvFeatureEvaluator.html',1,'cv']]],
  ['cvfeatureparams',['CvFeatureParams',['http://docs.opencv.org/4.0.1/db/dfc/classcv_1_1CvFeatureParams.html',1,'cv']]],
  ['cvhaarevaluator',['CvHaarEvaluator',['http://docs.opencv.org/4.0.1/db/d35/classcv_1_1CvHaarEvaluator.html',1,'cv']]],
  ['cvhaarfeatureparams',['CvHaarFeatureParams',['http://docs.opencv.org/4.0.1/d9/d90/classcv_1_1CvHaarFeatureParams.html',1,'cv']]],
  ['cvhaldft',['cvhalDFT',['http://docs.opencv.org/4.0.1/de/d27/structcvhalDFT.html',1,'']]],
  ['cvhalfilter2d',['cvhalFilter2D',['http://docs.opencv.org/4.0.1/d2/da8/structcvhalFilter2D.html',1,'']]],
  ['cvhalkeypoint',['cvhalKeyPoint',['http://docs.opencv.org/4.0.1/d9/daa/structcvhalKeyPoint.html',1,'']]],
  ['cvhogevaluator',['CvHOGEvaluator',['http://docs.opencv.org/4.0.1/d2/dd9/classcv_1_1CvHOGEvaluator.html',1,'cv']]],
  ['cvhogfeatureparams',['CvHOGFeatureParams',['http://docs.opencv.org/4.0.1/d4/d4a/structcv_1_1CvHOGFeatureParams.html',1,'cv']]],
  ['cvlbpevaluator',['CvLBPEvaluator',['http://docs.opencv.org/4.0.1/d1/d26/classcv_1_1CvLBPEvaluator.html',1,'cv']]],
  ['cvlbpfeatureparams',['CvLBPFeatureParams',['http://docs.opencv.org/4.0.1/d2/d3c/structcv_1_1CvLBPFeatureParams.html',1,'cv']]],
  ['cvparams',['CvParams',['http://docs.opencv.org/4.0.1/db/d7c/classcv_1_1CvParams.html',1,'cv']]],
  ['cvphotocamera',['CvPhotoCamera',['http://docs.opencv.org/4.0.1/d4/d1d/interfaceCvPhotoCamera.html',1,'']]],
  ['cvphotocameradelegate_20_2dp_2dp',['CvPhotoCameraDelegate -p-p',['http://docs.opencv.org/4.0.1/d7/d2f/protocolCvPhotoCameraDelegate_01-p.html',1,'']]],
  ['cvtype',['CvType',['http://docs.opencv.org/4.0.1/d1/def/structcv_1_1flann_1_1CvType.html',1,'cv::flann']]],
  ['cvtype_3c_20char_20_3e',['CvType&lt; char &gt;',['http://docs.opencv.org/4.0.1/dc/d89/structcv_1_1flann_1_1CvType_3_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20double_20_3e',['CvType&lt; double &gt;',['http://docs.opencv.org/4.0.1/dc/d69/structcv_1_1flann_1_1CvType_3_01double_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20float_20_3e',['CvType&lt; float &gt;',['http://docs.opencv.org/4.0.1/dc/dd6/structcv_1_1flann_1_1CvType_3_01float_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20short_20_3e',['CvType&lt; short &gt;',['http://docs.opencv.org/4.0.1/d2/def/structcv_1_1flann_1_1CvType_3_01short_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20char_20_3e',['CvType&lt; unsigned char &gt;',['http://docs.opencv.org/4.0.1/d7/da5/structcv_1_1flann_1_1CvType_3_01unsigned_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20short_20_3e',['CvType&lt; unsigned short &gt;',['http://docs.opencv.org/4.0.1/d9/d57/structcv_1_1flann_1_1CvType_3_01unsigned_01short_01_4.html',1,'cv::flann']]],
  ['cvvideocamera',['CvVideoCamera',['http://docs.opencv.org/4.0.1/db/da9/interfaceCvVideoCamera.html',1,'']]],
  ['cvvideocameradelegate_20_2dp_2dp',['CvVideoCameraDelegate -p-p',['http://docs.opencv.org/4.0.1/d3/d54/protocolCvVideoCameraDelegate_01-p.html',1,'']]],
  ['cylindricalportraitprojector',['CylindricalPortraitProjector',['http://docs.opencv.org/4.0.1/df/d3f/structcv_1_1detail_1_1CylindricalPortraitProjector.html',1,'cv::detail']]],
  ['cylindricalportraitwarper',['CylindricalPortraitWarper',['http://docs.opencv.org/4.0.1/dd/d19/classcv_1_1detail_1_1CylindricalPortraitWarper.html',1,'cv::detail']]],
  ['cylindricalprojector',['CylindricalProjector',['http://docs.opencv.org/4.0.1/dd/d96/structcv_1_1detail_1_1CylindricalProjector.html',1,'cv::detail']]],
  ['cylindricalwarper',['CylindricalWarper',['http://docs.opencv.org/4.0.1/d3/dd6/classcv_1_1detail_1_1CylindricalWarper.html',1,'cv::detail::CylindricalWarper'],['http://docs.opencv.org/4.0.1/d7/df6/classcv_1_1CylindricalWarper.html',1,'cv::CylindricalWarper']]],
  ['cylindricalwarpergpu',['CylindricalWarperGpu',['http://docs.opencv.org/4.0.1/d9/dbd/classcv_1_1detail_1_1CylindricalWarperGpu.html',1,'cv::detail']]]
];
