var searchData=
[
  ['daisy',['DAISY',['http://docs.opencv.org/4.0.1/d9/d37/classcv_1_1xfeatures2d_1_1DAISY.html',1,'cv::xfeatures2d']]],
  ['data',['Data',['http://docs.opencv.org/4.0.1/de/d4f/structcv_1_1face_1_1FacemarkAAM_1_1Data.html',1,'cv::face::FacemarkAAM']]],
  ['datadepth',['DataDepth',['http://docs.opencv.org/4.0.1/d7/d0e/classcv_1_1DataDepth.html',1,'cv']]],
  ['dataset',['Dataset',['http://docs.opencv.org/4.0.1/d9/d2e/classcv_1_1datasets_1_1Dataset.html',1,'cv::datasets']]],
  ['datatype',['Datatype',['http://docs.opencv.org/4.0.1/d4/dbd/structcvflann_1_1Datatype.html',1,'cvflann::Datatype&lt; class &gt;'],['http://docs.opencv.org/4.0.1/d0/d3a/classcv_1_1DataType.html',1,'cv::DataType&lt; class &gt;']]],
  ['datatype_3c_20char_20_3e',['Datatype&lt; char &gt;',['http://docs.opencv.org/4.0.1/d3/df4/structcvflann_1_1Datatype_3_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20double_20_3e',['Datatype&lt; double &gt;',['http://docs.opencv.org/4.0.1/d2/d8d/structcvflann_1_1Datatype_3_01double_01_4.html',1,'cvflann']]],
  ['datatype_3c_20float_20_3e',['Datatype&lt; float &gt;',['http://docs.opencv.org/4.0.1/dd/d42/structcvflann_1_1Datatype_3_01float_01_4.html',1,'cvflann']]],
  ['datatype_3c_20short_20_3e',['Datatype&lt; short &gt;',['http://docs.opencv.org/4.0.1/db/de5/structcvflann_1_1Datatype_3_01short_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20char_20_3e',['Datatype&lt; unsigned char &gt;',['http://docs.opencv.org/4.0.1/d3/dea/structcvflann_1_1Datatype_3_01unsigned_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20short_20_3e',['Datatype&lt; unsigned short &gt;',['http://docs.opencv.org/4.0.1/dc/dbe/structcvflann_1_1Datatype_3_01unsigned_01short_01_4.html',1,'cvflann']]],
  ['dct2d',['DCT2D',['http://docs.opencv.org/4.0.1/d5/d57/structcv_1_1hal_1_1DCT2D.html',1,'cv::hal']]],
  ['deblurerbase',['DeblurerBase',['http://docs.opencv.org/4.0.1/dd/d05/classcv_1_1videostab_1_1DeblurerBase.html',1,'cv::videostab']]],
  ['deconvolutionlayer',['DeconvolutionLayer',['http://docs.opencv.org/4.0.1/dd/d77/classcv_1_1dnn_1_1DeconvolutionLayer.html',1,'cv::dnn']]],
  ['defaultcopypolicy',['DefaultCopyPolicy',['http://docs.opencv.org/4.0.1/d8/dc2/structcv_1_1cudev_1_1DefaultCopyPolicy.html',1,'cv::cudev']]],
  ['defaultdeleter_3c_20cvcapture_20_3e',['DefaultDeleter&lt; CvCapture &gt;',['http://docs.opencv.org/4.0.1/d0/d90/structcv_1_1DefaultDeleter_3_01CvCapture_01_4.html',1,'cv']]],
  ['defaultdeleter_3c_20cvhaarclassifiercascade_20_3e',['DefaultDeleter&lt; CvHaarClassifierCascade &gt;',['http://docs.opencv.org/4.0.1/d9/ddf/structcv_1_1DefaultDeleter_3_01CvHaarClassifierCascade_01_4.html',1,'cv']]],
  ['defaultdeleter_3c_20cvvideowriter_20_3e',['DefaultDeleter&lt; CvVideoWriter &gt;',['http://docs.opencv.org/4.0.1/d2/d37/structcv_1_1DefaultDeleter_3_01CvVideoWriter_01_4.html',1,'cv']]],
  ['defaultglobreducepolicy',['DefaultGlobReducePolicy',['http://docs.opencv.org/4.0.1/d2/d04/structcv_1_1cudev_1_1DefaultGlobReducePolicy.html',1,'cv::cudev']]],
  ['defaulthistogrampolicy',['DefaultHistogramPolicy',['http://docs.opencv.org/4.0.1/d4/d2b/structcv_1_1cudev_1_1DefaultHistogramPolicy.html',1,'cv::cudev']]],
  ['defaultreducetovecpolicy',['DefaultReduceToVecPolicy',['http://docs.opencv.org/4.0.1/d3/dd7/structcv_1_1cudev_1_1DefaultReduceToVecPolicy.html',1,'cv::cudev']]],
  ['defaultsplitmergepolicy',['DefaultSplitMergePolicy',['http://docs.opencv.org/4.0.1/d9/d3a/structcv_1_1cudev_1_1DefaultSplitMergePolicy.html',1,'cv::cudev']]],
  ['defaulttransformpolicy',['DefaultTransformPolicy',['http://docs.opencv.org/4.0.1/db/db3/structcv_1_1cudev_1_1DefaultTransformPolicy.html',1,'cv::cudev']]],
  ['defaulttransposepolicy',['DefaultTransposePolicy',['http://docs.opencv.org/4.0.1/dd/d44/structcv_1_1cudev_1_1DefaultTransposePolicy.html',1,'cv::cudev']]],
  ['denseopticalflow',['DenseOpticalFlow',['http://docs.opencv.org/4.0.1/df/dde/classcv_1_1DenseOpticalFlow.html',1,'cv::DenseOpticalFlow'],['http://docs.opencv.org/4.0.1/d6/d4a/classcv_1_1cuda_1_1DenseOpticalFlow.html',1,'cv::cuda::DenseOpticalFlow']]],
  ['denseopticalflowext',['DenseOpticalFlowExt',['http://docs.opencv.org/4.0.1/d1/d21/classcv_1_1superres_1_1DenseOpticalFlowExt.html',1,'cv::superres']]],
  ['densepyrlkopticalflow',['DensePyrLKOpticalFlow',['http://docs.opencv.org/4.0.1/d0/da4/classcv_1_1cuda_1_1DensePyrLKOpticalFlow.html',1,'cv::cuda']]],
  ['depthcleaner',['DepthCleaner',['http://docs.opencv.org/4.0.1/d9/d5e/classcv_1_1rgbd_1_1DepthCleaner.html',1,'cv::rgbd']]],
  ['depthnormal',['DepthNormal',['http://docs.opencv.org/4.0.1/d7/d47/classcv_1_1linemod_1_1DepthNormal.html',1,'cv::linemod']]],
  ['derivxptr',['DerivXPtr',['http://docs.opencv.org/4.0.1/df/d8b/structcv_1_1cudev_1_1DerivXPtr.html',1,'cv::cudev']]],
  ['derivxptrsz',['DerivXPtrSz',['http://docs.opencv.org/4.0.1/db/d58/structcv_1_1cudev_1_1DerivXPtrSz.html',1,'cv::cudev']]],
  ['derivyptr',['DerivYPtr',['http://docs.opencv.org/4.0.1/dc/d51/structcv_1_1cudev_1_1DerivYPtr.html',1,'cv::cudev']]],
  ['derivyptrsz',['DerivYPtrSz',['http://docs.opencv.org/4.0.1/d2/dfc/structcv_1_1cudev_1_1DerivYPtrSz.html',1,'cv::cudev']]],
  ['descriptorcollection',['DescriptorCollection',['http://docs.opencv.org/4.0.1/d4/dac/classcv_1_1DescriptorMatcher_1_1DescriptorCollection.html',1,'cv::DescriptorMatcher']]],
  ['descriptorextractor',['descriptorExtractor',['http://docs.opencv.org/4.0.1/d7/d8d/classcv_1_1cnn__3dobj_1_1descriptorExtractor.html',1,'cv::cnn_3dobj']]],
  ['descriptormatcher',['DescriptorMatcher',['http://docs.opencv.org/4.0.1/db/d39/classcv_1_1DescriptorMatcher.html',1,'cv::DescriptorMatcher'],['http://docs.opencv.org/4.0.1/dd/dc5/classcv_1_1cuda_1_1DescriptorMatcher.html',1,'cv::cuda::DescriptorMatcher']]],
  ['detectionbasedtracker',['DetectionBasedTracker',['http://docs.opencv.org/4.0.1/db/de9/classcv_1_1DetectionBasedTracker.html',1,'cv']]],
  ['detectionoutputlayer',['DetectionOutputLayer',['http://docs.opencv.org/4.0.1/da/dbd/classcv_1_1dnn_1_1DetectionOutputLayer.html',1,'cv::dnn']]],
  ['detectionroi',['DetectionROI',['http://docs.opencv.org/4.0.1/d3/d34/structcv_1_1DetectionROI.html',1,'cv']]],
  ['detector',['Detector',['http://docs.opencv.org/4.0.1/de/db6/classcv_1_1Detector.html',1,'cv::Detector'],['http://docs.opencv.org/4.0.1/d7/d07/classcv_1_1linemod_1_1Detector.html',1,'cv::linemod::Detector']]],
  ['detectorparameters',['DetectorParameters',['http://docs.opencv.org/4.0.1/d1/dcd/structcv_1_1aruco_1_1DetectorParameters.html',1,'cv::aruco']]],
  ['device',['Device',['http://docs.opencv.org/4.0.1/d7/d9f/classcv_1_1ocl_1_1Device.html',1,'cv::ocl']]],
  ['deviceinfo',['DeviceInfo',['http://docs.opencv.org/4.0.1/d7/d7c/classcv_1_1cuda_1_1DeviceInfo.html',1,'cv::cuda']]],
  ['dft',['DFT',['http://docs.opencv.org/4.0.1/dc/de5/classcv_1_1cuda_1_1DFT.html',1,'cv::cuda']]],
  ['dft1d',['DFT1D',['http://docs.opencv.org/4.0.1/d8/d03/structcv_1_1hal_1_1DFT1D.html',1,'cv::hal']]],
  ['dft2d',['DFT2D',['http://docs.opencv.org/4.0.1/d6/d77/structcv_1_1hal_1_1DFT2D.html',1,'cv::hal']]],
  ['dict',['Dict',['http://docs.opencv.org/4.0.1/d9/d2b/classcv_1_1dnn_1_1Dict.html',1,'cv::dnn']]],
  ['dictionary',['Dictionary',['http://docs.opencv.org/4.0.1/d5/d0b/classcv_1_1aruco_1_1Dictionary.html',1,'cv::aruco']]],
  ['dictvalue',['DictValue',['http://docs.opencv.org/4.0.1/d4/db3/structcv_1_1dnn_1_1DictValue.html',1,'cv::dnn']]],
  ['direction_5ffunc',['direction_func',['http://docs.opencv.org/4.0.1/d3/d97/structcv_1_1cudev_1_1direction__func.html',1,'cv::cudev']]],
  ['disableif',['DisableIf',['http://docs.opencv.org/4.0.1/df/d27/structcv_1_1cudev_1_1DisableIf.html',1,'cv::cudev']]],
  ['disjointsets',['DisjointSets',['http://docs.opencv.org/4.0.1/dc/d3e/classcv_1_1detail_1_1DisjointSets.html',1,'cv::detail']]],
  ['disopticalflow',['DISOpticalFlow',['http://docs.opencv.org/4.0.1/de/d4f/classcv_1_1DISOpticalFlow.html',1,'cv']]],
  ['disparitybilateralfilter',['DisparityBilateralFilter',['http://docs.opencv.org/4.0.1/d8/d4f/classcv_1_1cuda_1_1DisparityBilateralFilter.html',1,'cv::cuda']]],
  ['disparityfilter',['DisparityFilter',['http://docs.opencv.org/4.0.1/db/d72/classcv_1_1ximgproc_1_1DisparityFilter.html',1,'cv::ximgproc']]],
  ['disparitywlsfilter',['DisparityWLSFilter',['http://docs.opencv.org/4.0.1/d9/d51/classcv_1_1ximgproc_1_1DisparityWLSFilter.html',1,'cv::ximgproc']]],
  ['distindex',['DistIndex',['http://docs.opencv.org/4.0.1/d0/d28/structcvflann_1_1UniqueResultSet_1_1DistIndex.html',1,'cvflann::UniqueResultSet']]],
  ['divides',['divides',['http://docs.opencv.org/4.0.1/de/d2a/structcv_1_1cudev_1_1divides.html',1,'cv::cudev']]],
  ['dmatch',['DMatch',['http://docs.opencv.org/4.0.1/d4/de0/classcv_1_1DMatch.html',1,'cv']]],
  ['downhillsolver',['DownhillSolver',['http://docs.opencv.org/4.0.1/d4/d43/classcv_1_1DownhillSolver.html',1,'cv']]],
  ['dpmdetector',['DPMDetector',['http://docs.opencv.org/4.0.1/df/dba/classcv_1_1dpm_1_1DPMDetector.html',1,'cv::dpm']]],
  ['dpseamfinder',['DpSeamFinder',['http://docs.opencv.org/4.0.1/d0/dd5/classcv_1_1detail_1_1DpSeamFinder.html',1,'cv::detail']]],
  ['drawlinesmatchesflags',['DrawLinesMatchesFlags',['http://docs.opencv.org/4.0.1/d8/d6f/structcv_1_1line__descriptor_1_1DrawLinesMatchesFlags.html',1,'cv::line_descriptor']]],
  ['dtfilter',['DTFilter',['http://docs.opencv.org/4.0.1/d3/d9d/classcv_1_1ximgproc_1_1DTFilter.html',1,'cv::ximgproc']]],
  ['dtrees',['DTrees',['http://docs.opencv.org/4.0.1/d8/d89/classcv_1_1ml_1_1DTrees.html',1,'cv::ml']]],
  ['dualtvl1opticalflow',['DualTVL1OpticalFlow',['http://docs.opencv.org/4.0.1/dc/d4d/classcv_1_1optflow_1_1DualTVL1OpticalFlow.html',1,'cv::optflow::DualTVL1OpticalFlow'],['http://docs.opencv.org/4.0.1/d6/db1/classcv_1_1superres_1_1DualTVL1OpticalFlow.html',1,'cv::superres::DualTVL1OpticalFlow']]],
  ['dynamicbitset',['DynamicBitset',['http://docs.opencv.org/4.0.1/d1/d73/classcvflann_1_1DynamicBitset.html',1,'cvflann']]],
  ['dynamicsharedmem',['DynamicSharedMem',['http://docs.opencv.org/4.0.1/d3/d2b/structcv_1_1cudev_1_1DynamicSharedMem.html',1,'cv::cudev']]],
  ['dynamicsharedmem_3c_20double_20_3e',['DynamicSharedMem&lt; double &gt;',['http://docs.opencv.org/4.0.1/db/d28/structcv_1_1cudev_1_1DynamicSharedMem_3_01double_01_4.html',1,'cv::cudev']]]
];
