var searchData=
[
  ['narymatiterator',['NAryMatIterator',['http://docs.opencv.org/4.0.1/d5/dd2/classcv_1_1NAryMatIterator.html',1,'cv']]],
  ['ncvbroxopticalflowdescriptor',['NCVBroxOpticalFlowDescriptor',['http://docs.opencv.org/4.0.1/db/d7a/structNCVBroxOpticalFlowDescriptor.html',1,'']]],
  ['ncvmatrix',['NCVMatrix',['http://docs.opencv.org/4.0.1/de/d26/classNCVMatrix.html',1,'']]],
  ['ncvmatrixalloc',['NCVMatrixAlloc',['http://docs.opencv.org/4.0.1/d7/d3a/classNCVMatrixAlloc.html',1,'']]],
  ['ncvmatrixreuse',['NCVMatrixReuse',['http://docs.opencv.org/4.0.1/df/d82/classNCVMatrixReuse.html',1,'']]],
  ['ncvmemnativeallocator',['NCVMemNativeAllocator',['http://docs.opencv.org/4.0.1/dc/d18/classNCVMemNativeAllocator.html',1,'']]],
  ['ncvmemptr',['NCVMemPtr',['http://docs.opencv.org/4.0.1/d6/d86/structNCVMemPtr.html',1,'']]],
  ['ncvmemsegment',['NCVMemSegment',['http://docs.opencv.org/4.0.1/d2/d12/structNCVMemSegment.html',1,'']]],
  ['ncvmemstackallocator',['NCVMemStackAllocator',['http://docs.opencv.org/4.0.1/db/d74/classNCVMemStackAllocator.html',1,'']]],
  ['ncvpoint2d32s',['NcvPoint2D32s',['http://docs.opencv.org/4.0.1/d5/d93/structNcvPoint2D32s.html',1,'']]],
  ['ncvpoint2d32u',['NcvPoint2D32u',['http://docs.opencv.org/4.0.1/dc/d16/structNcvPoint2D32u.html',1,'']]],
  ['ncvrect32s',['NcvRect32s',['http://docs.opencv.org/4.0.1/d3/dfe/structNcvRect32s.html',1,'']]],
  ['ncvrect32u',['NcvRect32u',['http://docs.opencv.org/4.0.1/d0/d62/structNcvRect32u.html',1,'']]],
  ['ncvrect8u',['NcvRect8u',['http://docs.opencv.org/4.0.1/da/d3f/structNcvRect8u.html',1,'']]],
  ['ncvsize32s',['NcvSize32s',['http://docs.opencv.org/4.0.1/d7/dda/structNcvSize32s.html',1,'']]],
  ['ncvsize32u',['NcvSize32u',['http://docs.opencv.org/4.0.1/d8/dde/structNcvSize32u.html',1,'']]],
  ['ncvvector',['NCVVector',['http://docs.opencv.org/4.0.1/dc/d73/classNCVVector.html',1,'']]],
  ['ncvvectoralloc',['NCVVectorAlloc',['http://docs.opencv.org/4.0.1/d8/da0/classNCVVectorAlloc.html',1,'']]],
  ['ncvvectorreuse',['NCVVectorReuse',['http://docs.opencv.org/4.0.1/da/d61/classNCVVectorReuse.html',1,'']]],
  ['nearestinterptr',['NearestInterPtr',['http://docs.opencv.org/4.0.1/d0/df5/structcv_1_1cudev_1_1NearestInterPtr.html',1,'cv::cudev']]],
  ['nearestinterptrsz',['NearestInterPtrSz',['http://docs.opencv.org/4.0.1/df/dd0/structcv_1_1cudev_1_1NearestInterPtrSz.html',1,'cv::cudev']]],
  ['negate',['negate',['http://docs.opencv.org/4.0.1/d9/d77/structcv_1_1cudev_1_1negate.html',1,'cv::cudev']]],
  ['net',['Net',['http://docs.opencv.org/4.0.1/db/d30/classcv_1_1dnn_1_1Net.html',1,'cv::dnn']]],
  ['nnindex',['NNIndex',['http://docs.opencv.org/4.0.1/d9/d10/classcvflann_1_1NNIndex.html',1,'cvflann']]],
  ['nnindex_3c_20cv_3a_3al1_3c_20elementtype_20_3e_20_3e',['NNIndex&lt; cv::L1&lt; ElementType &gt; &gt;',['http://docs.opencv.org/4.0.1/d9/d10/classcvflann_1_1NNIndex.html',1,'']]],
  ['nnindex_3c_20cv_3a_3al2_3c_20elementtype_20_3e_20_3e',['NNIndex&lt; cv::L2&lt; ElementType &gt; &gt;',['http://docs.opencv.org/4.0.1/d9/d10/classcvflann_1_1NNIndex.html',1,'']]],
  ['no',['No',['http://docs.opencv.org/4.0.1/dc/d5a/structcv_1_1cudev_1_1IsUnaryFunction_1_1No.html',1,'cv::cudev::IsUnaryFunction&lt; class &gt;::No'],['http://docs.opencv.org/4.0.1/db/d13/structcv_1_1cudev_1_1IsBinaryFunction_1_1No.html',1,'cv::cudev::IsBinaryFunction&lt; class &gt;::No']]],
  ['nobundleadjuster',['NoBundleAdjuster',['http://docs.opencv.org/4.0.1/db/dd4/classcv_1_1detail_1_1NoBundleAdjuster.html',1,'cv::detail']]],
  ['node',['Node',['http://docs.opencv.org/4.0.1/d2/d7d/structcv_1_1optflow_1_1GPCTree_1_1Node.html',1,'cv::optflow::GPCTree::Node'],['http://docs.opencv.org/4.0.1/d3/de3/classcv_1_1Node.html',1,'cv::Node&lt; OBJECT &gt;'],['http://docs.opencv.org/4.0.1/d4/d7d/classcv_1_1ml_1_1DTrees_1_1Node.html',1,'cv::ml::DTrees::Node'],['http://docs.opencv.org/4.0.1/d9/de0/structcv_1_1SparseMat_1_1Node.html',1,'cv::SparseMat::Node']]],
  ['nodedata',['NodeData',['http://docs.opencv.org/4.0.1/d7/dc2/classcv_1_1instr_1_1NodeData.html',1,'cv::instr']]],
  ['nodedatatls',['NodeDataTls',['http://docs.opencv.org/4.0.1/da/df1/structcv_1_1instr_1_1NodeDataTls.html',1,'cv::instr']]],
  ['noexposurecompensator',['NoExposureCompensator',['http://docs.opencv.org/4.0.1/d2/dc1/classcv_1_1detail_1_1NoExposureCompensator.html',1,'cv::detail']]],
  ['normalbayesclassifier',['NormalBayesClassifier',['http://docs.opencv.org/4.0.1/d4/d8e/classcv_1_1ml_1_1NormalBayesClassifier.html',1,'cv::ml']]],
  ['normalizebboxlayer',['NormalizeBBoxLayer',['http://docs.opencv.org/4.0.1/dc/df8/classcv_1_1dnn_1_1NormalizeBBoxLayer.html',1,'cv::dnn']]],
  ['normhamming',['NormHamming',['http://docs.opencv.org/4.0.1/d5/d7b/structcv_1_1cudev_1_1NormHamming.html',1,'cv::cudev']]],
  ['normhistogramcostextractor',['NormHistogramCostExtractor',['http://docs.opencv.org/4.0.1/df/d65/classcv_1_1NormHistogramCostExtractor.html',1,'cv']]],
  ['norml1',['NormL1',['http://docs.opencv.org/4.0.1/d7/df8/structcv_1_1cudev_1_1NormL1.html',1,'cv::cudev']]],
  ['norml1_3c_20float_20_3e',['NormL1&lt; float &gt;',['http://docs.opencv.org/4.0.1/d5/d1e/structcv_1_1cudev_1_1NormL1_3_01float_01_4.html',1,'cv::cudev']]],
  ['norml2',['NormL2',['http://docs.opencv.org/4.0.1/dc/da6/structcv_1_1cudev_1_1NormL2.html',1,'cv::cudev']]],
  ['noseamfinder',['NoSeamFinder',['http://docs.opencv.org/4.0.1/d3/da9/classcv_1_1detail_1_1NoSeamFinder.html',1,'cv::detail']]],
  ['not_5fequal_5fto',['not_equal_to',['http://docs.opencv.org/4.0.1/df/d9f/structcv_1_1cudev_1_1not__equal__to.html',1,'cv::cudev']]],
  ['nppstinterpolationstate',['NppStInterpolationState',['http://docs.opencv.org/4.0.1/da/da9/structNppStInterpolationState.html',1,'']]],
  ['nsobject',['NSObject',['http://docs.opencv.org/4.0.1/d4/d19/classNSObject.html',1,'']]],
  ['nsobject_2dp_2dp',['NSObject-p-p',['http://docs.opencv.org/4.0.1/d9/d15/classNSObject-p.html',1,'']]],
  ['nsobjectnsobject_2dp_2dp',['NSObjectNSObject-p-p',['http://docs.opencv.org/4.0.1/d5/d25/classNSObjectNSObject-p.html',1,'']]],
  ['nulldeblurer',['NullDeblurer',['http://docs.opencv.org/4.0.1/dc/d86/classcv_1_1videostab_1_1NullDeblurer.html',1,'cv::videostab']]],
  ['nullframesource',['NullFrameSource',['http://docs.opencv.org/4.0.1/dd/d5b/classcv_1_1videostab_1_1NullFrameSource.html',1,'cv::videostab']]],
  ['nullinpainter',['NullInpainter',['http://docs.opencv.org/4.0.1/d4/d1d/classcv_1_1videostab_1_1NullInpainter.html',1,'cv::videostab']]],
  ['nulllog',['NullLog',['http://docs.opencv.org/4.0.1/d6/d78/classcv_1_1videostab_1_1NullLog.html',1,'cv::videostab']]],
  ['nulloutlierrejector',['NullOutlierRejector',['http://docs.opencv.org/4.0.1/d3/de9/classcv_1_1videostab_1_1NullOutlierRejector.html',1,'cv::videostab']]],
  ['nulltype',['NullType',['http://docs.opencv.org/4.0.1/d5/d71/structcv_1_1cudev_1_1NullType.html',1,'cv::cudev']]],
  ['nullwobblesuppressor',['NullWobbleSuppressor',['http://docs.opencv.org/4.0.1/d0/da4/classcv_1_1videostab_1_1NullWobbleSuppressor.html',1,'cv::videostab']]],
  ['numeric_5flimits',['numeric_limits',['http://docs.opencv.org/4.0.1/db/dc8/structcv_1_1cudev_1_1numeric__limits.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20bool_20_3e',['numeric_limits&lt; bool &gt;',['http://docs.opencv.org/4.0.1/da/d81/structcv_1_1cudev_1_1numeric__limits_3_01bool_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20double_20_3e',['numeric_limits&lt; double &gt;',['http://docs.opencv.org/4.0.1/d2/d80/structcv_1_1cudev_1_1numeric__limits_3_01double_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20float_20_3e',['numeric_limits&lt; float &gt;',['http://docs.opencv.org/4.0.1/db/d88/structcv_1_1cudev_1_1numeric__limits_3_01float_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20schar_20_3e',['numeric_limits&lt; schar &gt;',['http://docs.opencv.org/4.0.1/da/d4e/structcv_1_1cudev_1_1numeric__limits_3_01schar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20short_20_3e',['numeric_limits&lt; short &gt;',['http://docs.opencv.org/4.0.1/d1/d8b/structcv_1_1cudev_1_1numeric__limits_3_01short_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uchar_20_3e',['numeric_limits&lt; uchar &gt;',['http://docs.opencv.org/4.0.1/d3/dc7/structcv_1_1cudev_1_1numeric__limits_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uint_20_3e',['numeric_limits&lt; uint &gt;',['http://docs.opencv.org/4.0.1/dd/d89/structcv_1_1cudev_1_1numeric__limits_3_01uint_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20ushort_20_3e',['numeric_limits&lt; ushort &gt;',['http://docs.opencv.org/4.0.1/df/d47/structcv_1_1cudev_1_1numeric__limits_3_01ushort_01_4.html',1,'cv::cudev']]]
];
