var searchData=
[
  ['hal_2ehpp',['hal.hpp',['http://docs.opencv.org/4.0.1/de/d0c/core_2include_2opencv2_2core_2hal_2hal_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d4/d44/imgproc_2include_2opencv2_2imgproc_2hal_2hal_8hpp.html',1,'(Global Namespace)']]],
  ['hal_5freplacement_2ehpp',['hal_replacement.hpp',['http://docs.opencv.org/4.0.1/db/ddd/core_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/df/d91/imgproc_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d2/dd9/features2d_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)']]],
  ['harris_5fdetector_2emarkdown',['harris_detector.markdown',['http://docs.opencv.org/4.0.1/db/d48/harris__detector_8markdown.html',1,'']]],
  ['hdf_2ehpp',['hdf.hpp',['http://docs.opencv.org/4.0.1/d7/d55/hdf_8hpp.html',1,'']]],
  ['hdf5_2ehpp',['hdf5.hpp',['http://docs.opencv.org/4.0.1/de/d24/hdf5_8hpp.html',1,'']]],
  ['hdr_5fimaging_2emarkdown',['hdr_imaging.markdown',['http://docs.opencv.org/4.0.1/d9/d87/hdr__imaging_8markdown.html',1,'']]],
  ['heap_2eh',['heap.h',['http://docs.opencv.org/4.0.1/da/ddb/heap_8h.html',1,'']]],
  ['hello_2emarkdown',['hello.markdown',['http://docs.opencv.org/4.0.1/da/da0/hello_8markdown.html',1,'']]],
  ['hfs_2ehpp',['hfs.hpp',['http://docs.opencv.org/4.0.1/de/d29/hfs_8hpp.html',1,'']]],
  ['hierarchical_5fclustering_5findex_2eh',['hierarchical_clustering_index.h',['http://docs.opencv.org/4.0.1/de/d1d/hierarchical__clustering__index_8h.html',1,'']]],
  ['highgui_2ehpp',['highgui.hpp',['http://docs.opencv.org/4.0.1/d0/dce/highgui_2highgui_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d4/dd5/highgui_8hpp.html',1,'(Global Namespace)']]],
  ['highgui_5fwinrt_2ehpp',['highgui_winrt.hpp',['http://docs.opencv.org/4.0.1/d9/d22/highgui__winrt_8hpp.html',1,'']]],
  ['hist_5fcost_2ehpp',['hist_cost.hpp',['http://docs.opencv.org/4.0.1/df/d08/hist__cost_8hpp.html',1,'']]],
  ['histo3d_2emarkdown',['histo3D.markdown',['http://docs.opencv.org/4.0.1/df/dd7/histo3D_8markdown.html',1,'']]],
  ['histogram_2ehpp',['histogram.hpp',['http://docs.opencv.org/4.0.1/d5/d6e/histogram_8hpp.html',1,'']]],
  ['histogram_5fcalculation_2emarkdown',['histogram_calculation.markdown',['http://docs.opencv.org/4.0.1/d2/d3a/histogram__calculation_8markdown.html',1,'']]],
  ['histogram_5fcomparison_2emarkdown',['histogram_comparison.markdown',['http://docs.opencv.org/4.0.1/de/d12/histogram__comparison_8markdown.html',1,'']]],
  ['histogram_5fequalization_2emarkdown',['histogram_equalization.markdown',['http://docs.opencv.org/4.0.1/db/de8/histogram__equalization_8markdown.html',1,'']]],
  ['histogramphaseunwrapping_2ehpp',['histogramphaseunwrapping.hpp',['http://docs.opencv.org/4.0.1/df/dce/histogramphaseunwrapping_8hpp.html',1,'']]],
  ['hitormiss_2emarkdown',['hitOrMiss.markdown',['http://docs.opencv.org/4.0.1/d2/dbf/hitOrMiss_8markdown.html',1,'']]],
  ['homography_2emarkdown',['homography.markdown',['http://docs.opencv.org/4.0.1/d2/dc8/homography_8markdown.html',1,'']]],
  ['hough_5fcircle_2emarkdown',['hough_circle.markdown',['http://docs.opencv.org/4.0.1/d4/d67/hough__circle_8markdown.html',1,'']]],
  ['hough_5flines_2emarkdown',['hough_lines.markdown',['http://docs.opencv.org/4.0.1/da/d5a/hough__lines_8markdown.html',1,'']]],
  ['how_5fto_5fcreate_5fgroups_2emarkdown',['how_to_create_groups.markdown',['http://docs.opencv.org/4.0.1/d7/d7b/how__to__create__groups_8markdown.html',1,'']]],
  ['how_5fto_5fscan_5fimages_2emarkdown',['how_to_scan_images.markdown',['http://docs.opencv.org/4.0.1/d5/d91/how__to__scan__images_8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fopencv_5fparallel_5ffor_5f_2emarkdown',['how_to_use_OpenCV_parallel_for_.markdown',['http://docs.opencv.org/4.0.1/d5/d45/how__to__use__OpenCV__parallel__for___8markdown.html',1,'']]],
  ['hpe_5fhumaneva_2ehpp',['hpe_humaneva.hpp',['http://docs.opencv.org/4.0.1/d8/da7/hpe__humaneva_8hpp.html',1,'']]],
  ['hpe_5fparse_2ehpp',['hpe_parse.hpp',['http://docs.opencv.org/4.0.1/da/da9/hpe__parse_8hpp.html',1,'']]],
  ['hull_2emarkdown',['hull.markdown',['http://docs.opencv.org/4.0.1/d0/dbd/hull_8markdown.html',1,'']]]
];
