var searchData=
[
  ['data_5fgeneration_2emarkdown',['data_generation.markdown',['http://docs.opencv.org/4.0.1/d5/d8e/data__generation_8markdown.html',1,'']]],
  ['datamov_5futils_2ehpp',['datamov_utils.hpp',['http://docs.opencv.org/4.0.1/df/dcf/datamov__utils_8hpp.html',1,'']]],
  ['dataset_2ehpp',['dataset.hpp',['http://docs.opencv.org/4.0.1/dc/d6a/dataset_8hpp.html',1,'']]],
  ['dct_5fimage_5fdenoising_2ehpp',['dct_image_denoising.hpp',['http://docs.opencv.org/4.0.1/da/dd8/dct__image__denoising_8hpp.html',1,'']]],
  ['deblurring_2ehpp',['deblurring.hpp',['http://docs.opencv.org/4.0.1/d4/db5/deblurring_8hpp.html',1,'']]],
  ['debug_5fmode_2ehpp',['debug_mode.hpp',['http://docs.opencv.org/4.0.1/d1/d9f/debug__mode_8hpp.html',1,'']]],
  ['defines_2eh',['defines.h',['http://docs.opencv.org/4.0.1/d8/db0/defines_8h.html',1,'']]],
  ['depth_2ehpp',['depth.hpp',['http://docs.opencv.org/4.0.1/db/d30/depth_8hpp.html',1,'']]],
  ['deriche_5ffilter_2ehpp',['deriche_filter.hpp',['http://docs.opencv.org/4.0.1/d4/d71/deriche__filter_8hpp.html',1,'']]],
  ['deriv_2ehpp',['deriv.hpp',['http://docs.opencv.org/4.0.1/df/d27/expr_2deriv_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/dd/da3/ptr2d_2deriv_8hpp.html',1,'(Global Namespace)']]],
  ['descriptor_2ehpp',['descriptor.hpp',['http://docs.opencv.org/4.0.1/db/d82/line__descriptor_2include_2opencv2_2line__descriptor_2descriptor_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d8/db0/stereo_2include_2opencv2_2stereo_2descriptor_8hpp.html',1,'(Global Namespace)']]],
  ['detection_5fbased_5ftracker_2ehpp',['detection_based_tracker.hpp',['http://docs.opencv.org/4.0.1/d5/d5a/detection__based__tracker_8hpp.html',1,'']]],
  ['detection_5fof_5fplanar_5fobjects_2emarkdown',['detection_of_planar_objects.markdown',['http://docs.opencv.org/4.0.1/dd/d5c/detection__of__planar__objects_8markdown.html',1,'']]],
  ['dev_5fwith_5focv_5fon_5fandroid_2emarkdown',['dev_with_OCV_on_Android.markdown',['http://docs.opencv.org/4.0.1/d9/d37/dev__with__OCV__on__Android_8markdown.html',1,'']]],
  ['dict_2ehpp',['dict.hpp',['http://docs.opencv.org/4.0.1/df/de6/dict_8hpp.html',1,'']]],
  ['dictionary_2ehpp',['dictionary.hpp',['http://docs.opencv.org/4.0.1/dc/df7/dictionary_8hpp.html',1,'']]],
  ['directx_2ehpp',['directx.hpp',['http://docs.opencv.org/4.0.1/df/d8b/directx_8hpp.html',1,'']]],
  ['discrete_5ffourier_5ftransform_2emarkdown',['discrete_fourier_transform.markdown',['http://docs.opencv.org/4.0.1/d7/d0e/discrete__fourier__transform_8markdown.html',1,'']]],
  ['disparity_5ffilter_2ehpp',['disparity_filter.hpp',['http://docs.opencv.org/4.0.1/da/d08/disparity__filter_8hpp.html',1,'']]],
  ['disparity_5ffiltering_2emarkdown',['disparity_filtering.markdown',['http://docs.opencv.org/4.0.1/d1/de3/disparity__filtering_8markdown.html',1,'']]],
  ['display_5fimage_2emarkdown',['display_image.markdown',['http://docs.opencv.org/4.0.1/dd/d8a/display__image_8markdown.html',1,'']]],
  ['dist_2eh',['dist.h',['http://docs.opencv.org/4.0.1/d1/d82/dist_8h.html',1,'']]],
  ['distance_5ftransform_2emarkdown',['distance_transform.markdown',['http://docs.opencv.org/4.0.1/dc/d15/distance__transform_8markdown.html',1,'']]],
  ['dmatch_2ehpp',['dmatch.hpp',['http://docs.opencv.org/4.0.1/d7/de1/dmatch_8hpp.html',1,'']]],
  ['dnn_2ehpp',['dnn.hpp',['http://docs.opencv.org/4.0.1/db/ddc/dnn_2dnn_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d9/d8c/dnn_8hpp.html',1,'(Global Namespace)']]],
  ['dnn_5fandroid_2emarkdown',['dnn_android.markdown',['http://docs.opencv.org/4.0.1/de/d6f/dnn__android_8markdown.html',1,'']]],
  ['dnn_5fcustom_5flayers_2emd',['dnn_custom_layers.md',['http://docs.opencv.org/4.0.1/d6/ddf/dnn__custom__layers_8md.html',1,'']]],
  ['dnn_5fgooglenet_2emarkdown',['dnn_googlenet.markdown',['http://docs.opencv.org/4.0.1/dc/d31/dnn__googlenet_8markdown.html',1,'']]],
  ['dnn_5fhalide_2emarkdown',['dnn_halide.markdown',['http://docs.opencv.org/4.0.1/d0/d59/dnn__halide_8markdown.html',1,'']]],
  ['dnn_5fhalide_5fscheduling_2emarkdown',['dnn_halide_scheduling.markdown',['http://docs.opencv.org/4.0.1/d6/d74/dnn__halide__scheduling_8markdown.html',1,'']]],
  ['dnn_5fjavascript_2emarkdown',['dnn_javascript.markdown',['http://docs.opencv.org/4.0.1/da/d1b/dnn__javascript_8markdown.html',1,'']]],
  ['dnn_5fobjdetect_5ftutorial_2emarkdown',['dnn_objdetect_tutorial.markdown',['http://docs.opencv.org/4.0.1/dd/d87/dnn__objdetect__tutorial_8markdown.html',1,'']]],
  ['dnn_5fyolo_2emarkdown',['dnn_yolo.markdown',['http://docs.opencv.org/4.0.1/dd/dfb/dnn__yolo_8markdown.html',1,'']]],
  ['documentation_5ftutorial_2emarkdown',['documentation_tutorial.markdown',['http://docs.opencv.org/4.0.1/d6/d6b/documentation__tutorial_8markdown.html',1,'']]],
  ['dpm_2ehpp',['dpm.hpp',['http://docs.opencv.org/4.0.1/da/d8a/dpm_8hpp.html',1,'']]],
  ['dummy_2eh',['dummy.h',['http://docs.opencv.org/4.0.1/d2/d94/dummy_8h.html',1,'']]],
  ['dynamic_5fbitset_2eh',['dynamic_bitset.h',['http://docs.opencv.org/4.0.1/da/d5c/dynamic__bitset_8h.html',1,'']]],
  ['dynamic_5fsmem_2ehpp',['dynamic_smem.hpp',['http://docs.opencv.org/4.0.1/d3/d73/modules_2core_2include_2opencv2_2core_2cuda_2dynamic__smem_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d1/d15/contrib_2modules_2cudev_2include_2opencv2_2cudev_2block_2dynamic__smem_8hpp.html',1,'(Global Namespace)']]]
];
