var searchData=
[
  ['calib3d_2ehpp',['calib3d.hpp',['http://docs.opencv.org/4.0.1/d7/de4/calib3d_2calib3d_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d2/d28/calib3d_8hpp.html',1,'(Global Namespace)']]],
  ['call_5fmeta_5fdata_2ehpp',['call_meta_data.hpp',['http://docs.opencv.org/4.0.1/da/da7/call__meta__data_8hpp.html',1,'']]],
  ['camera_2ehpp',['camera.hpp',['http://docs.opencv.org/4.0.1/d0/d8a/camera_8hpp.html',1,'']]],
  ['camera_5fcalibration_2emarkdown',['camera_calibration.markdown',['http://docs.opencv.org/4.0.1/d8/d78/camera__calibration_8markdown.html',1,'']]],
  ['camera_5fcalibration_5fsquare_5fchess_2emarkdown',['camera_calibration_square_chess.markdown',['http://docs.opencv.org/4.0.1/de/d59/camera__calibration__square__chess_8markdown.html',1,'']]],
  ['canny_5fdetector_2emarkdown',['canny_detector.markdown',['http://docs.opencv.org/4.0.1/d0/d6f/canny__detector_8markdown.html',1,'']]],
  ['cap_5fios_2eh',['cap_ios.h',['http://docs.opencv.org/4.0.1/d9/d4d/cap__ios_8h.html',1,'']]],
  ['cap_5fwinrt_2ehpp',['cap_winrt.hpp',['http://docs.opencv.org/4.0.1/d7/d64/cap__winrt_8hpp.html',1,'']]],
  ['capture_5fpattern_2emarkdown',['capture_pattern.markdown',['http://docs.opencv.org/4.0.1/d5/df3/capture__pattern_8markdown.html',1,'']]],
  ['capturesinpattern_2emarkdown',['capturesinpattern.markdown',['http://docs.opencv.org/4.0.1/d4/d9d/capturesinpattern_8markdown.html',1,'']]],
  ['cascade_5fclassifier_2emarkdown',['cascade_classifier.markdown',['http://docs.opencv.org/4.0.1/d0/d98/cascade__classifier_8markdown.html',1,'']]],
  ['ccalib_2ehpp',['ccalib.hpp',['http://docs.opencv.org/4.0.1/d6/d01/ccalib_8hpp.html',1,'']]],
  ['changelog_2emarkdown',['changelog.markdown',['http://docs.opencv.org/4.0.1/de/d0f/changelog_8markdown.html',1,'']]],
  ['charuco_2ehpp',['charuco.hpp',['http://docs.opencv.org/4.0.1/da/d3b/charuco_8hpp.html',1,'']]],
  ['charuco_5fdetection_2emarkdown',['charuco_detection.markdown',['http://docs.opencv.org/4.0.1/d2/df7/charuco__detection_8markdown.html',1,'']]],
  ['charuco_5fdiamond_5fdetection_2emarkdown',['charuco_diamond_detection.markdown',['http://docs.opencv.org/4.0.1/d8/d54/charuco__diamond__detection_8markdown.html',1,'']]],
  ['check_2ehpp',['check.hpp',['http://docs.opencv.org/4.0.1/d1/d26/check_8hpp.html',1,'']]],
  ['classify_2emarkdown',['classify.markdown',['http://docs.opencv.org/4.0.1/d4/d6a/classify_8markdown.html',1,'']]],
  ['clojure_5fdev_5fintro_2emarkdown',['clojure_dev_intro.markdown',['http://docs.opencv.org/4.0.1/da/d37/clojure__dev__intro_8markdown.html',1,'']]],
  ['cnn_5f3dobj_2ehpp',['cnn_3dobj.hpp',['http://docs.opencv.org/4.0.1/de/d45/cnn__3dobj_8hpp.html',1,'']]],
  ['color_2ehpp',['color.hpp',['http://docs.opencv.org/4.0.1/d1/d71/modules_2core_2include_2opencv2_2core_2cuda_2color_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/dc/d7a/contrib_2modules_2cudev_2include_2opencv2_2cudev_2expr_2color_8hpp.html',1,'(Global Namespace)']]],
  ['color_5fcvt_2ehpp',['color_cvt.hpp',['http://docs.opencv.org/4.0.1/db/dcf/color__cvt_8hpp.html',1,'']]],
  ['color_5fmatch_2ehpp',['color_match.hpp',['http://docs.opencv.org/4.0.1/da/dc9/color__match_8hpp.html',1,'']]],
  ['color_5fmoment_5fhash_2ehpp',['color_moment_hash.hpp',['http://docs.opencv.org/4.0.1/d1/d01/color__moment__hash_8hpp.html',1,'']]],
  ['colors_2emarkdown',['colors.markdown',['http://docs.opencv.org/4.0.1/db/d92/colors_8markdown.html',1,'']]],
  ['common_2ehpp',['common.hpp',['http://docs.opencv.org/4.0.1/dc/d9d/modules_2core_2include_2opencv2_2core_2cuda_2common_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/da/de9/contrib_2modules_2cudev_2include_2opencv2_2cudev_2common_8hpp.html',1,'(Global Namespace)']]],
  ['compiler_5fhints_2ehpp',['compiler_hints.hpp',['http://docs.opencv.org/4.0.1/d6/d2e/compiler__hints_8hpp.html',1,'']]],
  ['composite_5findex_2eh',['composite_index.h',['http://docs.opencv.org/4.0.1/d1/d7b/composite__index_8h.html',1,'']]],
  ['conditioning_2ehpp',['conditioning.hpp',['http://docs.opencv.org/4.0.1/d7/d09/conditioning_8hpp.html',1,'']]],
  ['config_2eh',['config.h',['http://docs.opencv.org/4.0.1/db/d16/config_8h.html',1,'']]],
  ['configuration_2eprivate_2ehpp',['configuration.private.hpp',['http://docs.opencv.org/4.0.1/d3/d08/configuration_8private_8hpp.html',1,'']]],
  ['constant_2ehpp',['constant.hpp',['http://docs.opencv.org/4.0.1/d8/dbf/constant_8hpp.html',1,'']]],
  ['container_5favi_2eprivate_2ehpp',['container_avi.private.hpp',['http://docs.opencv.org/4.0.1/d2/db0/container__avi_8private_8hpp.html',1,'']]],
  ['contrib_5ftutorials_2emarkdown',['contrib_tutorials.markdown',['http://docs.opencv.org/4.0.1/dd/df3/contrib__tutorials_8markdown.html',1,'']]],
  ['convert_2ehpp',['convert.hpp',['http://docs.opencv.org/4.0.1/df/d32/convert_8hpp.html',1,'']]],
  ['copy_2ehpp',['copy.hpp',['http://docs.opencv.org/4.0.1/d7/deb/copy_8hpp.html',1,'']]],
  ['copymakeborder_2emarkdown',['copyMakeBorder.markdown',['http://docs.opencv.org/4.0.1/d5/dca/copyMakeBorder_8markdown.html',1,'']]],
  ['core_2ehpp',['core.hpp',['http://docs.opencv.org/4.0.1/d2/ddb/core_2include_2opencv2_2core_2core_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d0/d9c/core_2include_2opencv2_2core_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d4/df9/gapi_2include_2opencv2_2gapi_2core_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d4/df2/gapi_2include_2opencv2_2gapi_2cpu_2core_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d3/d81/gapi_2include_2opencv2_2gapi_2fluid_2core_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d9/d1a/gapi_2include_2opencv2_2gapi_2gpu_2core_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/dd/db3/gapi_2include_2opencv2_2gapi_2ocl_2core_8hpp.html',1,'(Global Namespace)']]],
  ['core_5fdetect_2ehpp',['core_detect.hpp',['http://docs.opencv.org/4.0.1/dd/d1b/core__detect_8hpp.html',1,'']]],
  ['corner_5fsubpixels_2emarkdown',['corner_subpixels.markdown',['http://docs.opencv.org/4.0.1/dc/d29/corner__subpixels_8markdown.html',1,'']]],
  ['create_5fread_5fwrite_5fdataset_2emarkdown',['create_read_write_dataset.markdown',['http://docs.opencv.org/4.0.1/db/d27/create__read__write__dataset_8markdown.html',1,'']]],
  ['creating_5fwidgets_2emarkdown',['creating_widgets.markdown',['http://docs.opencv.org/4.0.1/da/d9a/creating__widgets_8markdown.html',1,'']]],
  ['cuda_2ehpp',['cuda.hpp',['http://docs.opencv.org/4.0.1/d8/dd1/modules_2core_2include_2opencv2_2core_2cuda_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d2/d7d/modules_2photo_2include_2opencv2_2photo_2cuda_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/da/d44/contrib_2modules_2xfeatures2d_2include_2opencv2_2xfeatures2d_2cuda_8hpp.html',1,'(Global Namespace)']]],
  ['cuda_2emarkdown',['cuda.markdown',['http://docs.opencv.org/4.0.1/d5/d00/cuda_8markdown.html',1,'']]],
  ['cuda_5fstream_5faccessor_2ehpp',['cuda_stream_accessor.hpp',['http://docs.opencv.org/4.0.1/d3/de8/cuda__stream__accessor_8hpp.html',1,'']]],
  ['cuda_5ftypes_2ehpp',['cuda_types.hpp',['http://docs.opencv.org/4.0.1/de/db2/cuda__types_8hpp.html',1,'']]],
  ['cudaarithm_2ehpp',['cudaarithm.hpp',['http://docs.opencv.org/4.0.1/d4/d03/cudaarithm_8hpp.html',1,'']]],
  ['cudabgsegm_2ehpp',['cudabgsegm.hpp',['http://docs.opencv.org/4.0.1/dc/d3d/cudabgsegm_8hpp.html',1,'']]],
  ['cudacodec_2ehpp',['cudacodec.hpp',['http://docs.opencv.org/4.0.1/dd/d4e/cudacodec_8hpp.html',1,'']]],
  ['cudafeatures2d_2ehpp',['cudafeatures2d.hpp',['http://docs.opencv.org/4.0.1/d7/d0a/cudafeatures2d_8hpp.html',1,'']]],
  ['cudafilters_2ehpp',['cudafilters.hpp',['http://docs.opencv.org/4.0.1/da/dc5/cudafilters_8hpp.html',1,'']]],
  ['cudaimgproc_2ehpp',['cudaimgproc.hpp',['http://docs.opencv.org/4.0.1/de/de4/cudaimgproc_8hpp.html',1,'']]],
  ['cudalegacy_2ehpp',['cudalegacy.hpp',['http://docs.opencv.org/4.0.1/da/d10/cudalegacy_8hpp.html',1,'']]],
  ['cudaobjdetect_2ehpp',['cudaobjdetect.hpp',['http://docs.opencv.org/4.0.1/d2/df3/cudaobjdetect_8hpp.html',1,'']]],
  ['cudaoptflow_2ehpp',['cudaoptflow.hpp',['http://docs.opencv.org/4.0.1/d2/d43/cudaoptflow_8hpp.html',1,'']]],
  ['cudastereo_2ehpp',['cudastereo.hpp',['http://docs.opencv.org/4.0.1/d8/d60/cudastereo_8hpp.html',1,'']]],
  ['cudawarping_2ehpp',['cudawarping.hpp',['http://docs.opencv.org/4.0.1/d1/d3d/cudawarping_8hpp.html',1,'']]],
  ['cudev_2ehpp',['cudev.hpp',['http://docs.opencv.org/4.0.1/d6/d38/cudev_8hpp.html',1,'']]],
  ['cv_5fcpu_5fdispatch_2eh',['cv_cpu_dispatch.h',['http://docs.opencv.org/4.0.1/d1/dac/cv__cpu__dispatch_8h.html',1,'']]],
  ['cv_5fcpu_5fhelper_2eh',['cv_cpu_helper.h',['http://docs.opencv.org/4.0.1/d2/d3b/cv__cpu__helper_8h.html',1,'']]],
  ['cv_5fcpu_5finclude_5fsimd_5fdeclarations_2ehpp',['cv_cpu_include_simd_declarations.hpp',['http://docs.opencv.org/4.0.1/d2/d7c/cv__cpu__include__simd__declarations_8hpp.html',1,'']]],
  ['cvdef_2eh',['cvdef.h',['http://docs.opencv.org/4.0.1/dc/dcc/cvdef_8h.html',1,'']]],
  ['cvdefs_2ehpp',['cvdefs.hpp',['http://docs.opencv.org/4.0.1/df/da4/cvdefs_8hpp.html',1,'']]],
  ['cvstd_2ehpp',['cvstd.hpp',['http://docs.opencv.org/4.0.1/dd/dc7/cvstd_8hpp.html',1,'']]],
  ['cvstd_5fwrapper_2ehpp',['cvstd_wrapper.hpp',['http://docs.opencv.org/4.0.1/d7/d47/cvstd__wrapper_8hpp.html',1,'']]],
  ['cvv_2ehpp',['cvv.hpp',['http://docs.opencv.org/4.0.1/d2/dcf/cvv_2cvv_8hpp.html',1,'(Global Namespace)'],['http://docs.opencv.org/4.0.1/d4/d7f/cvv_8hpp.html',1,'(Global Namespace)']]]
];
