var searchData=
[
  ['camera_20calibration_20and_203d_20reconstruction',['Camera Calibration and 3D Reconstruction',['http://docs.opencv.org/4.0.1/d9/d0c/group__calib3d.html',1,'']]],
  ['c_20api',['C API',['http://docs.opencv.org/4.0.1/d5/db8/group__calib3d__c.html',1,'']]],
  ['custom_20calibration_20pattern_20for_203d_20reconstruction',['Custom Calibration Pattern for 3D reconstruction',['http://docs.opencv.org/4.0.1/d3/ddc/group__ccalib.html',1,'']]],
  ['conditioning',['Conditioning',['http://docs.opencv.org/4.0.1/da/d8b/group__conditioning.html',1,'']]],
  ['core_20functionality',['Core functionality',['http://docs.opencv.org/4.0.1/d0/de1/group__core.html',1,'']]],
  ['c_20structures_20and_20operations',['C structures and operations',['http://docs.opencv.org/4.0.1/d2/df8/group__core__c.html',1,'']]],
  ['connections_20with_20c_2b_2b',['Connections with C++',['http://docs.opencv.org/4.0.1/d8/dd7/group__core__c__glue.html',1,'']]],
  ['clustering',['Clustering',['http://docs.opencv.org/4.0.1/d5/d38/group__core__cluster.html',1,'']]],
  ['cholesky_20matrix_20decomposition',['Cholesky matrix decomposition',['http://docs.opencv.org/4.0.1/d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'']]],
  ['channel_20merge',['Channel merge',['http://docs.opencv.org/4.0.1/df/d2e/group__core__hal__interface__merge.html',1,'']]],
  ['channel_20split',['Channel split',['http://docs.opencv.org/4.0.1/df/df2/group__core__hal__interface__split.html',1,'']]],
  ['core_5flogging',['Core_logging',['http://docs.opencv.org/4.0.1/d3/dcb/group__core__logging.html',1,'']]],
  ['core_5futils_5fvsx',['Core_utils_vsx',['http://docs.opencv.org/4.0.1/d3/d50/group__core__utils__vsx.html',1,'']]],
  ['cuda_2daccelerated_20computer_20vision',['CUDA-accelerated Computer Vision',['http://docs.opencv.org/4.0.1/d1/d1e/group__cuda.html',1,'']]],
  ['core_20operations_20on_20matrices',['Core Operations on Matrices',['http://docs.opencv.org/4.0.1/de/d09/group__cudaarithm__core.html',1,'']]],
  ['core_20part',['Core part',['http://docs.opencv.org/4.0.1/d7/d05/group__cudacore.html',1,'']]],
  ['color_20space_20processing',['Color space processing',['http://docs.opencv.org/4.0.1/db/d8c/group__cudaimgproc__color.html',1,'']]],
  ['clustering_20and_20search_20in_20multi_2ddimensional_20spaces',['Clustering and Search in Multi-Dimensional Spaces',['http://docs.opencv.org/4.0.1/dc/de5/group__flann.html',1,'']]],
  ['c_20api',['C API',['http://docs.opencv.org/4.0.1/d0/d28/group__highgui__c.html',1,'']]],
  ['c_20api',['C API',['http://docs.opencv.org/4.0.1/da/d0a/group__imgcodecs__c.html',1,'']]],
  ['c_20api',['C API',['http://docs.opencv.org/4.0.1/df/d4e/group__imgproc__c.html',1,'']]],
  ['color_20space_20conversions',['Color Space Conversions',['http://docs.opencv.org/4.0.1/d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['colormaps_20in_20opencv',['ColorMaps in OpenCV',['http://docs.opencv.org/4.0.1/d3/d50/group__imgproc__colormap.html',1,'']]],
  ['c_20api',['C API',['http://docs.opencv.org/4.0.1/d9/d31/group__objdetect__c.html',1,'']]],
  ['computational_20photography',['Computational Photography',['http://docs.opencv.org/4.0.1/d1/d0d/group__photo.html',1,'']]],
  ['c_20api',['C API',['http://docs.opencv.org/4.0.1/d3/d40/group__photo__c.html',1,'']]],
  ['c_20api',['C API',['http://docs.opencv.org/4.0.1/d3/d12/group__video__c.html',1,'']]],
  ['c_20api_20for_20video_20i_2fo',['C API for video I/O',['http://docs.opencv.org/4.0.1/dd/d01/group__videoio__c.html',1,'']]]
];
